---
title: "Frequently Asked Questions"
description: ""
site: distill::distill_website
---


```{css, echo = FALSE}
d-title {
    display: none;
    }
    
d-article h2 {
    margin-top: 0;
    margin-bottom: 1em;
    margin-left: -3em;
    margin-right: 0;
}

d-article h3 {
    margin-top: 0;
    margin-bottom: 1em;
    margin-left: -5em;
    margin-right: 0;
}
d-article p, d-article ul, d-article blockquote {
    margin-top: 0;
    margin-bottom: 1em;
    margin-left: -6em;
    margin-right: 0;
    width: 135%;
}



```


<div style="text-align: justify;">


<br> <br>


## Registration Questions

### How do I get into your (full) class?

Psychology advising holds back seats in the initial registration period, so there's a good chance that the "full" class you see on DuckWeb isn't actually full. Depending on the class size, there could be 5, or 25, or more unfilled seats that will eventually be added. Psych advising waits for classes to fill and then gives out the rest of these seats based on need. Their waitlist will rank graduating seniors first and anyone that needs a particular course in order to progress through the major. Professors don't interfere with this process (even if we could) because it would be unfair to other students who need to be in the class or won't have another opportunity to take it. You can e-mail psychology advising to get on the waitlist for psychology courses (psyugadvisors@uoregon.edu) or drop into their [advising hours](https://blogs.uoregon.edu/psychologyresources/human-subjects-pool/drop-in-advising-schedule/) on the second floor of Straub.

## Research Questions

### Can I apply to be a research assistant in your lab?

I'm a teaching professor, so I don't have a research lab. Psychology professors (with titles assistant professor, associate professor, and professor) typically teach 2 - 3 undergraduate (+ 1 graduate or seminar) classes per year and run a research lab with graduate students, whereas psychology teaching professors typically teach 9 undergraduate classes per year and focus on developing curriculum instead of research. If you're interested in social and personality psychology, you might be interested in joining: 

- Dr. Sara Hodges's [Social Cognition Lab](https://socialcognitionlab.uoregon.edu/)
- Dr. Chanel Meyers and Dr. Curtis Phills's [Diversity & Social Cognition Lab](https://www.diversitysocialcoglab.com/join-us)
- Dr. Ellen Peters's [Cognitive and Affective Influences in Decision Making Lab](https://www.caidelab.com/)
- Dr. Rob Chavez's [Computational Social Neuroscience Lab](https://csnl.uoregon.edu/)
- Dr. Elliot Berkman's [Social & Affective Neuroscience Lab](https://sanlab.uoregon.edu/)

Many of the lab websites have an apply section with an application, and they hire on an as need basis (usually to start at the beginning of a new term for course credit). [Psychology advising](https://naturalsciences.uoregon.edu/psychology/undergraduate-programs/dept-advising) also may know which labs are actively searching for research assistants. If you have interests in other psychology subfields like clinical, cognitive, or developmental psychology, you can search the [faculty directory](https://cas.uoregon.edu/directory/psychology-faculty?page=0) for professors with interests that align with yours. Clicking on their name will usually bring up more information including their lab website if they have one. 

This process is very competitive, but I strongly recommend joining a lab if you can because it'll really bring to life what you're learning in your classes. It’s also a great way to explore whether research is something you want to pursue as a career. Research experience is typically a non-negotiable if you plan to pursue a PhD in psychology.

## Graduate School Questions

### Will you write me a letter of recommendation?

See the [LOR tab on this website](https://sdimakis.github.io/lor.html) for a detailed explanation of my reference letter process. 

### What do I need to do to get a strong letter of recommendation from you?

Please keep in mind that I teach around 250 - 450 students every term, which means I have a ton of former students requesting letters. If you're in a large lecture with me, I recommend that you sit in the first row in class, come to class consistently, and raise your hand when I ask questions. If you don't feel comfortable talking in front of the whole class, you can always come up after class to ask questions or make comments about the lecture or course content that demonstrates to me that you were actively engaged and thinking deeply about it. Take more than one class with me, preferably over several terms, so we can get to know each other over time. Definitely take my moral psychology course, because there's only 50 students in that class, and it's a discussion heavy class. When we interact, remind me your name and how we've met before. Come to office hours to talk to me about your goals. To talk to me about your assignments. To talk to me about what you're taking from the course. I'd love to get to know you as a person, beyond the work you produce in the classes, and this will make for a far better letter.

### Should I go to graduate school?

I recommend going to graduate school only if you have a clear idea of the job you would like to pursue afterward, have researched and talked with (or listened to) multiple people about their experiences with that job (the good AND the bad), that job aligns with your interests, skills, and values, and graduate school is necessary to get hired in the profession. Graduate school is a major commitment, and it's not a decision that needs to be made immediately. Taking a gap year is very common. I took a year between undergraduate and graduate school, and many people wait much longer, sometimes five to ten years, while others return to school after an entirely different first career. I don't recommend graduate school if your primary reason is that you want to learn more psychology (or figure out more about what you're interested in). There are a lot of ways to learn more psychology (including many accessible [books](https://www.goodreads.com/review/list/68649668-sarah-dimakis?shelf=read), podcasts, and online lectures by researchers) without incurring the financial costs or opportunity costs associated with pursuing an unnecessary degree.

### How do I get into graduate school for a PhD in social psychology?

PhD programs are extremely competitive and more akin to a getting a job (any program worth going to will pay you a stipend to get the degree through being a TA or researcher) than applying to college or other graduate programs (where you are paying the college to attend). It's a huge investment for the university and department to train a graduate researcher, and they want to make sure that you have the content knowledge, ability, and motivation to stick with it. You'll need excellent grades, relevant research experience (see: joining a lab), excellent research fit with the faculty member you're asking to mentor you, and strong letters of rec (see: letters of recommendation). They also want to see character traits like independence, grit, and integrity. Many faculty mentors expect you to have publications or a master's degree. You should expect to move states and potentially not get in on your first year of applying. I completed my PhD in social psychology in 2024 at UO, and am always happy to talk at length about my experiences in graduate school (the highs and the lows).

### How do I get into graduate school for a career in mental health?

This is very common path for a psychology major. I didn't personally go to graduate school for mental health (I studied social psychology), but here are some resources that I hear are helpful.

- [Psychology advising drop in hours](https://blogs.uoregon.edu/psychologyresources/human-subjects-pool/drop-in-advising-schedule/) -- look for graduate students or faculty with "clinical" research interests
- [Mitch Prinstein's Graduate School Advice](https://mitch.web.unc.edu/wp-content/uploads/sites/4922/2017/02/MitchGradSchoolAdvice.pdf) -- helpful descriptions of the different mental health fields and degrees 
- [Getting into grad school](https://www.clinicalpsychphd.com/home) -- example personal statements and CVs
- [Insider's guide to graduate programs in clinical and counseling psychology](https://www.guilford.com/books/Insiders-Guide-Graduate-Programs-Clinical-Counseling-Psychology/Norcross-Sayette/9781462563029?srsltid=AfmBOoqp4-Q4YJEb7oXkJDVZnnM6QJ9Uy45fiFBcrZRzECkGjc74cRIa) by John Norcross & Michael Sayette (not free)


## Teaching Philosophy & Course Design Questions

### What advice do you have for a student who got a grade they're unhappy with?

College gives us the chance to try new things, fail, accept those failures, take responsibility, and learn from them in a low-stakes environment. Failure often teaches us more about ourselves than success does. Sometimes failure reveals that our goals are not aligned with our values, interests, or strengths. Other times, it reflects the reality that we have competing priorities and school can't (and shouldn't) always be our top one. Sometimes failure is the result of a very normal human mistake, such as forgetting to study a particular topic or misunderstanding an assignment. Your grades (and generally, any outcome in life) will not always fully reflect your abilities or potential, and learning to come to terms with this is extremely valuable for your well-being. In my view, one of the most valuable lessons college can teach is how to respond to setbacks with grace and resilience. Unfortunately, people who never experience failure often miss the opportunity to develop those skills. In my view, students who challenge themselves will inevitably encounter failure and setbacks towards their goals. I certainly did. I didn't earn straight A's because I often chose courses that interested me, requiring skills I was weak at but wanted to develop (like public speaking), even when I wasn't sure I would excel in them. What mattered more to me was the opportunity to learn and grow. I never want students to be afraid of trying something new because they might fail. 

### Why aren't you grading attendance anymore in your large lecture classes?

I want to grade students on the extent to which they meet the learning objectives, and coming to class to engage with other students is one way (but not the only way) to demonstrate that you've met my objective to communicate about the content. When someone asks a question or makes an insightful comment in class, the entire class benefits, and we all learn more deeply for it. I wish I could award course credit for that, but it's not really practical. I also think it's too subjective. In the past, I've relied on iClicker to take attendance (a poor but easy and objective indicator of engagement), but it's becoming increasingly unreliable, expensive, and easy to gain. It's also very time consuming to grade and respond to e-mails about. I'd rather spend my time making sure class is worth going to than policing whether students are there. I do really appreciate students who thoughtfully answer questions in class, and they are rewarded with (generally) better grades for less effort, and glowing letters of recommendation from me. So I think it's a fair trade-off.

### Why don't you record your lectures?

I don't record lectures because it makes me and other students uncomfortable to be monitored like that. The tech glitches a lot, and it makes in-person class a worse experience. It makes students less likely to come to class or be engaged during class if they know a recording is being made. The AEC works with students to assess and determine accommodations for those who need them. When students need them (temporarily due to injury or permanently), they can get accommodations to record audio of my lectures or a peer note taker. 

### Why do you only assess with homework and exams (not projects)?

Projects can be really fun, but they can also be extremely frustrating and daunting, depending on your group and your capacity to meet outside of class hours. Many students work part or full time, are in clubs or sports teams with demanding time requirements, or have caretaker responsibilities outside of class. I also think grading on groupwork is unfair. Grades should be based on the extent to which an individual student met the learning objectives of the course, not based on who they happen to get in their group. I do always hope and encourage students to meet others in my classes, learn from each other in in-class discussions, and work on assignments together, but I don't think students should be forced to do so.

## Personal Questions


### What breed is your dog?

Zucchini is a 6-year-old "lab-mix". Maybe some Chihuahua or Dachshund (she's VERY long).  Absolutely no idea beyond that. I have not given her a DNA test. I adopted her when she was 3 from the [Rawley Project](https://www.therawleyproject.org/) out in Bend.

### Don't you have a cat too? You never talk about her.

Yes.

### What font do you use for all of your materials?

It's called Crimson Text. It's a google font that you can download [here]( https://fonts.google.com/specimen/Crimson+Text).

### Why do you use so many exclamation points when you e-mail me?

I want you to know I'm not mad at you. No it's fine you didn't turn in your work! 

### What do you like to do outside of work?

I mostly enjoy "productive hobbies" like cooking, exercising, and building things, but I also enjoy things like Jigsaw puzzles, video games (mostly farming simulation games lol), and watching psychologically interesting true crime documentaries. 

### What was your graduate research about?

I studied moral person perception, mainly thinking about how we make assumptions that someone has unobservable or unobserved immoral characteristics. If you're interested, you can read my dissertation [here](https://scholarsbank.uoregon.edu/items/925ce272-b0df-4e1f-b421-c4edb9d1cef0).