---
title: "Letters of Recommendation"
description: ""
site: distill::distill_website
---

```{css, echo = FALSE}

    
d-title {
    display: none;
    }
    
d-article h2 {
    margin-top: 0;
    margin-bottom: 1em;
    margin-left: -3em;
    margin-right: 0;
}

d-article h3 {
    margin-top: 0;
    margin-bottom: 1em;
    margin-left: -5em;
    margin-right: 0;
}
d-article p, d-article ul, d-article blockquote {
    margin-top: 0;
    margin-bottom: 1em;
    margin-left: -6em;
    margin-right: 0;
    width: 135%;
}
    

```
<div style="text-align: justify;">


<br> <br>


## Letters of Recommendation

I often write letters of recommendation and serve as academic references for students applying to tutoring positions, research assistant roles, PSY202 peer lab leader positions, university scholarships, and graduate school applications. Please keep in mind that I typically teach 250 - 450 students every term, and the number of former students requesting letters grows each year. Because of this, I am generally unable to write letters or serve as a reference for students I have only interacted with in a large lecture setting, as I probably don't know them well enough to provide a personalized letter. I am more flexible about this for psychology department positions like tutoring, research assistant, and peer lab positions, but it can seriously harm your graduate school application to have a letter from someone who doesn't know you very well (and I have to tell them how well I know you). I can only serve as an **academic reference**, meaning I cannot act as a reference for employment or housing applications that specifically request a former employer.

I write the strongest letters for students who have participated a lot (and meaningfully) in multiple of my classes (especially my smallest class, moral psychology) and have come to my office hours to talk more deeply about course content. I can also typically write strong letters for students who have had me both in class and on their psychology honors thesis committee (e.g., primary adviser, 2nd reader). Receiving an "A" (or even an "A+") in one or more of my courses is not sufficient (nor required) for me to write a strong letter for you. However, in general, if you earned a "B" or lower in my course(s), I may need to rank you in the lower half of applicants if asked directly. In these situations, I typically recommend finding another letter writer who can provide a stronger endorsement. I accept most requests, but I may decline if I believe my letter would weaken your application or I already committed to too many reference requests. This typically occurs when:

- The request is submitted fewer than **two weeks** before your earliest deadline
- I have major concerns about academic integrity, such as over-reliance on generative AI tools in your written coursework, suspected cheating during exams, inappropriate requests for make up exams or deadline extensions, or requests to "bump up" your grade
- There is a substantial mismatch between your performance in my course(s) or experience and the expectations of the position, program, or scholarship you are applying to (e.g., you are applying to a research intensive program like a PhD without extensive research experience)
- We have little or no prior relationship and the request includes flattery (e.g., I just LOVED your teaching)

To initiate a letter of recommendation request, I recommend explaining in an e-mail or in office hours (1) how we know each other (e.g., which classes of mine you took and when), (2) what you are applying for, and (3) when the deadlines are. If I determine that I'm a good fit to write you a letter, I will send you a Google Form requesting the following information:

- The application deadline(s) (this must be at least 2 weeks away from when you submit the Goggle Form)
- A description of the position or program you're applying to 
- A statement of purpose explaining why you're applying to the program or position 
- Your top three academic strengths that are relevant to the position or program, along with specific examples of how you demonstrated those strengths in my course(s). For example: "I demonstrated strong critical thinking skills in your class when..."
- An unofficial transcript (optional, highly suggested for graduate school applications and university scholarships)
- Your CV or resume (optional, highly suggested for graduate school applications and university scholarships)
- The name of the research professor(s) who has supervised your research and/ or list of your research publications (for PhD graduate school only)

</div>