---
title: "Teaching Philosophy"
description: ""
site: distill::distill_website
---

<div style="text-align: justify;">


```{css, echo = FALSE}

    
d-article h2{
    display: none !important;
    }
    
.btn {
  color: #6da444 !important;                
  text-decoration: none !important;          
  padding: 2px 2px;            
  font-size: 18px;              
  font-weight: bold;            
  margin-right: 10px;          
  display: inline-flex;          
  align-items: center;           
  gap: 8px;                     
  transition: background-color 0.3s ease, transform 0.2s ease;
   border: 2px;
}
.btn:hover {
  transform: translateY(-2px); 
  text-decoration: none !important; 
  border: 1px;
}

d-title {
    display: none;
    }
    

```

<br> <br>

# Teaching Philosophy

My role as a psychology teacher is to curate and clearly articulate what scientists currently understand about the human mind and behavior and to channel students’ natural curiosity and enthusiasm as they begin to engage with and contribute to that developing body of knowledge. I mostly teach large (~100-150 students per section) 300-level undergraduate courses, where my primary goal is to ensure that students retain the foundational knowledge and skills necessary to succeed in their future specialized coursework. Once students fully understand core psychological theories, methods, and findings, they are well equipped to challenge widely held assumptions about their own minds and behaviors, engage critically with published research, and seek empirically grounded answers to the questions they care most deeply about. I teach psychology because I believe learning about psychology research makes us wiser consumers of information, and teaches us how to live a happy and satisfying life.

Learning is not just a one-way transfer of information from professor to student, but an interactive process that requires effort, patience, and an open mind from both parties. I use a dynamic lecturing approach that integrates the formal presentation of theory with evidence like research findings and personal applications, and activities like demonstrations, discussions, and practice questions. In lecture, you can expect to learn new theories, apply them in class in small or large-group discussions with your classmates, and then explore them more deeply or personally through your homework assignments. These active components enhance retention of the material, focus and sustain attention, and make learning (an effortful and sometimes daunting process) genuinely more enjoyable.

One of the most frustrating parts of learning is to feel that you are being unfairly or opaquely assessed. I am committed to designing assignments that clearly connect to the learning goals of the course, are intrinsically motivating to complete, help students master both skills and content, are fair and accurate assessments of content knowledge, and encourage learning and continual growth. I typically assess content knowledge with in-person multiple choice and short answer exams and weekly homework assignments. In my classes, you can expect straightforward study guides, clear rubrics, and full transparency about the purpose and grading of each assignment.

Starting Winter 2026, I am no longer grading attendance for my 300-level classes, but my moral psychology class will always have a class engagement component (requiring attendance). I try to be more flexible with attendance when you are forced to take my class because it's a requirement to progress through the major (not an elective). However, generally, if you're looking for a class you can take but not attend, my classes might not be for you. I have had some students succeed in the past when needing to miss a lot of classes for medical or personal issues, but these are the exceptions and the rule is generally that low attendance requires more effort for less pay off. I do not record my in-person lectures, but I do post my slides in case you have to miss class (most students who get an "A" in the course will naturally have to miss 1 - 3 lectures). I do not 'flip' my classes or assign group work (although I always encourage collaboration for studying and homework) because, in practice, I believe these approaches have more drawbacks than benefits. I know some people really like these approaches to learning, and I can recommend other professors who use them if you ask!

Regardless of the subject matter, I will always ensure the following three elements occur in my classroom: 


# Application 

*“Tell me and I forget, teach me and I may remember, involve me and I learn.”* - Xun Kuang

The purpose of a psychology education should not be to memorize a set of related facts, but to learn how to apply those facts in ways that foster personal growth and a deeper understanding of oneself and others. Application to one’s prior experiences and knowledge serves both as a source of motivation to stay engaged and as a primer that new material can adhere to and build upon. In my courses, I design assignments that encourage students to reflect on how the course content connects to and deepens our understanding of ourselves and others. For example, in my moral psychology course, students analyze contemporary case studies and apply psychological theories to explain real-world events (e.g., why are most people reluctant to hold Gypsy-Rose Blanchard fully responsible for her role in her mother’s murder)? In my social psychology course, students apply theory to assess the effectiveness of advertisements they encounter. In my personality psychology course, students complete and critique personality assessments to gain a better understanding of their own traits and how their traits impact their lives. These assignments encourage students to consider the broader value of mastering the material beyond short-term goals like doing well on their exams or improving their GPA. 

# Critical Thinking  

*“It is the mark of an educated mind to be able to entertain a thought without accepting it.”* - Aristotle

One of the most concerning issues of our time is the widespread proliferation of false and misleading information. An educated person must be able to assess the validity of claims and evaluate the strength of the evidence supporting them. A psychology education provides an ideal context for developing these skills. A key part of engaging with scientific research is learning when to agree with and when to question its conclusions. When I teach scientific thinking, students learn that studying methodology gives them the tools to critically evaluate scientific work. Students complete assignments that guide them through critiques of empirical studies and their coverage in the media. We examine why research often fails to replicate, and how scientists have evolved practices and safeguards to increase the rigor of their work. This approach helps students critically evaluate scientific findings and recognize that science is a self-correcting process that produces stable conclusions over time. In my social and moral psychology classes, I often ask students to question their widely held assumptions and beliefs when they conflict with psychological research. For example, students discuss the surprising evidence that empathy can sometimes harm our moral judgment, or that people tend to conform to others they know are wrong.

# Inclusivity

*“People will forget what you said. People will forget what you did. But people will never forget how you made them feel.”* – Maya Angelou

It's important to me that students feel safe approaching me with questions or concerns and trust that I am invested in their learning and success. Trust and human connection are difficult to build in large classes yet necessary for meaningful learning. I hope to create a classroom environment where no one feels judged or inferior for not yet knowing something, and where every student feels their unique perspective is valued and contributes to our collective learning. I attended a small college where my psychology classes typically ranged from 10 to 40 students, and I try to make every one of my classrooms feel that small and personal. Even though I mostly teach large lecture courses, I hope to connect with each student individually through my office hours, class participation, and reading and giving individualized feedback on their work. I don’t believe such a relationship can be fully developed in a single term, so I try to teach a variety of courses that allow students to take multiple classes with me and build that trust and connection over time. In my social and moral psychology classes, I often teach complex and emotionally charged topics such as stereotyping, prejudice, intergroup bias, and moral differences, and I approach these subjects with scientific curiosity and respect for diverse viewpoints. I understand the importance of representation and strive to be a positive role model for the identities I hold, and to foster a classroom environment where students feel comfortable sharing their own perspectives and engaging with those of others. I prioritize affordability in my courses by using free or low-cost materials whenever possible. I am committed to making my courses accessible for students navigating difficult life circumstances by having reason-neutral flexible policies for late-work or missed exams.

I hope to infect my students with the same passion and excitement for psychology research and data that I have, but even if not, I hope each student leaves my classroom better prepared to engage thoughtfully with scientific research throughout their lives. I hope they leave with new insights about themselves and others. I hope they reconnect with how fun it is to learn new things. And I hope they leave with tools and ideas to live a happy and meaningful life.

# Selected Course Evaluations

*"Learning about things in the way we did made the information insightful and applicable to so many different instances. I found myself thinking more deeply about concepts and engaging with the content unintentionally in my free time because it intertwines well with everything in my life."* - Scientific Thinking, Fall '25

*"The homeworks and critiques we did in this course required us to directly use the content we had been covering, and were somewhat cumulative of that knowledge base. I had to engage myself entirely to feel confident in the product I submitted.”* - Scientific Thinking, Fall '24

*"[Sarah] teaches a searingly uninteresting topic in a way that makes it incredibly interesting and easy to learn."* - Scientific Thinking, Fall '24

*“Any time I had any questions she would sit with me and explain thoroughly until I understood and was so patient it made me feel so comfortable asking for help.”* - Statistical Methods in Psychology, Spring '25

*“Sarah repeats information well without making it boring, the syllabus is extremely clear, the material is well described, and lecture slides are accessible. I loved this course in part due to this, as having clarity aids my learning and time management.”* – Statistical Methods in Psychology, Spring '25

*“Sarah creates a dynamic where the information is highly retainable, and the workload is manageable. An ideal class set up!”* – Social Psychology, Winter '25

*“Social psychology is a class that has helped me put a lot of aspects of my life into perspective. It has taught me how this world works, how humans work, and how we can work for and against each other. I feel like this class has opened a new world of awareness for me when it comes to how humans interact with each other, and why we do what we do.”* – Social Psychology, Winter '25

*“Really interesting course but also incredibly dark at times. I wish this class was a year long.”* – Social Psychology, Winter '25

*"I love how you connected the concepts we were learning about back to our lives. I felt like I could learn more about myself."* - Personality Psychology, Fall '25

*"Every homework tied to the course content, the lectures were highly organized, squeezing tons of good information and citations into our limited class-time. The course material was obviously very well researched, with many insights from Sarah. The in-class discussions also fostered insights from our whole classroom, with many students injecting interesting ideas about personality interactions."* - Personality Psychology, Fall '25

*“I have never had this much fun learning in a psych class and have never retained this much information this easily. I can see myself using almost everything that was taught in the future, and have a newfound massive interest to continue learning about moral psych.”* – Moral Psychology, Winter '25

*"I definitely feel this class has called on me to question my morals (in a good way) and to better consider the viewpoints of others. I also feel Professor Dimakis fostered a very nice classroom environment. Though we discussed rather divisive topics, I never felt my opinion was unvalued or criticized. The lectures were also very clear and well laid out. Professor Dimakis is also funny while still being informative, making it easy to stay focused in class.”*  – Moral Psychology, Winter '25

*"While most classes regarding morality are from a philosophical perspective on how we ought to behave, this one was really interesting in covering how we actually behave and why... I’ve always been baffled by how most people’s sense of morality doesn’t follow what I consider a logical framework. This class helped me understand the basis of what I’ve always perceived as inconsistency and on a personal level has helped me understand how I can be more harmonious with people I have differing views from... I think this class would be a great elective choice for students considering law school."* - Moral Psychology, Fall '25

</div>